BLD-390 Capture mongod stdout and stderr to a separate log file

diff --git a/debian/percona-server-mongodb-server.mongod.init b/debian/percona-server-mongodb-server.mongod.init
--- a/debian/percona-server-mongodb-server.mongod.init
+++ b/debian/percona-server-mongodb-server.mongod.init
@@ -60,6 +60,12 @@ PIDDIR=$(dirname $PIDFILEPATH)
 ENABLE_MONGOD=yes
 MONGO_USER=${MONGO_USER:-mongod}
 MONGO_GROUP=${MONGO_GROUP:-mongod}
+STARTTIME=1
+DIETIME=10                  
+# Time to wait for the server to die, in seconds
+# If this value is set too low you might not
+# let some servers to die gracefully and
+# 'restart' will not work
 
 
 # Include mongodb defaults if available
@@ -73,89 +79,82 @@ DAEMON_OPTS="${OPTIONS}"
 NUMACTL_ARGS="--interleave=all"
 if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
 then
-    NUMACTL="`which numactl` -- $NUMACTL_ARGS"
-    DAEMON_OPTS=${DAEMON_OPTS:-"--config $CONF"}
+  NUMACTL="`which numactl` -- $NUMACTL_ARGS"
+  DAEMON_OPTS=${DAEMON_OPTS:-"--config $CONF"}
 else
-    NUMACTL=""
-    DAEMON_OPTS="-- "${DAEMON_OPTS:-"--config $CONF"}
+  NUMACTL=""
+  DAEMON_OPTS="-- "${DAEMON_OPTS:-"--config $CONF"}
 fi
 
 if test ! -x $DAEMON; then
-    echo "Could not find $DAEMON"
-    exit 0
+  echo "Could not find $DAEMON"
+  exit 0
 fi
 
 if test "x$ENABLE_MONGOD" != "xyes"; then
-    exit 0
+  exit 0
 fi
 
 . /lib/lsb/init-functions
-
-STARTTIME=1
-DIETIME=10                   # Time to wait for the server to die, in seconds
-                            # If this value is set too low you might not
-                            # let some servers to die gracefully and
-                            # 'restart' will not work
 
 set -e
 
 running_pid() {
 # Check if a given process pid's cmdline matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
-    # Is this the expected server
-    [ "$cmd" != "$name" ] &&  return 1
-    return 0
+  pid=$1
+  name=$2
+  [ -z "$pid" ] && return 1
+  [ ! -d /proc/$pid ] &&  return 1
+  cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
+# Is this the expected server
+  [ "$cmd" != "$name" ] &&  return 1
+  return 0
 }
 
 running() {
 # Check if the process is running looking at /proc
 # (works for all users)
 
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILEPATH" ] && return 1
-    pid=`cat $PIDFILEPATH`
-    running_pid $pid $DAEMON || return 1
-    return 0
+# No pidfile, probably no daemon present
+  [ ! -f "$PIDFILEPATH" ] && return 1
+  pid=`cat $PIDFILEPATH`
+  running_pid $pid $DAEMON || return 1
+  return 0
 }
 
 start_server() {
-            # Recommended ulimit values for mongod or mongos
-            # See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
-            #
-            ulimit -f unlimited
-            ulimit -t unlimited
-            ulimit -v unlimited
-            ulimit -n 64000
-            ulimit -m unlimited
+# Recommended ulimit values for mongod or mongos
+# See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
+#
+  ulimit -f unlimited
+  ulimit -t unlimited
+  ulimit -v unlimited
+  ulimit -n 64000
+  ulimit -m unlimited
 
-            # In dash, ulimit takes -p for maximum user processes
-            # In bash, it's -u
-            if readlink /proc/$$/exe | grep -q dash
-            then
-                    ulimit -p 64000
-            else
-                    ulimit -u 64000
-            fi
+# In dash, ulimit takes -p for maximum user processes
+# In bash, it's -u
+  if readlink /proc/$$/exe | grep -q dash
+  then
+    ulimit -p 64000
+  else
+    ulimit -u 64000
+  fi
 
-            # Start the process using the wrapper
-            /usr/bin/percona-server-mongodb-helper.sh
-            start-stop-daemon --background --start --quiet --pidfile $PIDFILEPATH \
-                        --make-pidfile --chuid $MONGO_USER \
-                        --exec $NUMACTL $DAEMON $DAEMON_OPTS
-            errcode=$?
+# Start the process using the wrapper
+  /usr/bin/percona-server-mongodb-helper.sh
+  start-stop-daemon -C --background --start --quiet --pidfile $PIDFILEPATH \
+  --make-pidfile --chuid ${MONGO_USER} \
+  --exec ${NUMACTL} ${DAEMON} ${DAEMON_OPTS} > ${STDOUT} 2> ${STDERR}
+  errcode=$?
 	return $errcode
 }
 
 stop_server() {
 # Stop the process using the wrapper
-            start-stop-daemon --stop --quiet --pidfile $PIDFILEPATH \
-                        --retry 300 \
-                        --user $MONGO_USER
-            errcode=$?
+  start-stop-daemon --stop --quiet --pidfile $PIDFILEPATH \
+  --retry 300 --user $MONGO_USER
+  errcode=$?
 	return $errcode
 }
 
@@ -181,87 +180,85 @@ force_stop() {
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
-        # Check if it's running first
-        if running ;  then
-            log_progress_msg "apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
-        if start_server ; then
-            # NOTE: Some servers might die some time after they start,
-            # this code will detect this issue if STARTTIME is set
-            # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
-            if  running ;  then
-                # It's ok, the server started and is running
-                log_end_msg 0
-            else
-                # It is not running after we did start
-                log_end_msg 1
-            fi
-        else
-            # Either we could not start it
-            log_end_msg 1
-        fi
+    log_daemon_msg "Starting $DESC" "$NAME"
+# Check if it's running first
+    if running ;  then
+      log_progress_msg "apparently already running"
+      log_end_msg 0
+      exit 0
+    fi
+
+    if start_server ; then
+# NOTE: Some servers might die some time after they start,
+# this code will detect this issue if STARTTIME is set
+# to a reasonable value
+      [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
+      if  running ;  then
+# It's ok, the server started and is running
+        log_end_msg 0
+      else
+# It is not running after we did start
+        log_end_msg 1
+      fi
+    else
+# Either we could not start it
+      log_end_msg 1
+    fi
 	;;
   stop)
-        log_daemon_msg "Stopping $DESC" "$NAME"
-        if running ; then
-            # Only stop the server if we see it running
-			errcode=0
-            stop_server || errcode=$?
-            log_end_msg $errcode
-        else
-            # If it's not running don't do anything
-            log_progress_msg "apparently not running"
-            log_end_msg 0
-            exit 0
-        fi
+    log_daemon_msg "Stopping $DESC" "$NAME"
+      if running ; then
+# Only stop the server if we see it running
+        errcode=0
+        stop_server || errcode=$?
+        log_end_msg $errcode
+      else
+# If it's not running don't do anything
+        log_progress_msg "apparently not running"
+        log_end_msg 0
+        exit 0
+      fi
         ;;
   force-stop)
-        # First try to stop gracefully the program
-        $0 stop
-        if running; then
-            # If it's still running try to kill it more forcefully
-            log_daemon_msg "Stopping (force) $DESC" "$NAME"
+# First try to stop gracefully the program
+    $0 stop
+    if running; then
+# If it's still running try to kill it more forcefully
+      log_daemon_msg "Stopping (force) $DESC" "$NAME"
 			errcode=0
-            force_stop || errcode=$?
-            log_end_msg $errcode
-        fi
+      force_stop || errcode=$?
+      log_end_msg $errcode
+    fi
 	;;
   restart|force-reload)
-        log_daemon_msg "Restarting $DESC" "$NAME"
+    log_daemon_msg "Restarting $DESC" "$NAME"
 		errcode=0
-        stop_server || errcode=$?
-        # Wait some sensible amount, some server need this
-        [ -n "$DIETIME" ] && sleep $DIETIME
-        start_server || errcode=$?
-        [ -n "$STARTTIME" ] && sleep $STARTTIME
-        running || errcode=$?
-        log_end_msg $errcode
+    stop_server || errcode=$?
+# Wait some sensible amount, some server need this
+    [ -n "$DIETIME" ] && sleep $DIETIME
+    start_server || errcode=$?
+    [ -n "$STARTTIME" ] && sleep $STARTTIME
+    running || errcode=$?
+    log_end_msg $errcode
 	;;
   status)
-
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if running ;  then
-            log_progress_msg "running"
-            log_end_msg 0
-        else
-            log_progress_msg "apparently not running"
-            log_end_msg 1
-            exit 1
-        fi
-        ;;
+  log_daemon_msg "Checking status of $DESC" "$NAME"
+  if running ;  then
+    log_progress_msg "running"
+    log_end_msg 0
+  else
+    log_progress_msg "apparently not running"
+    log_end_msg 1
+    exit 1
+  fi
+  ;;
   # MongoDB can't reload its configuration.
   reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
-        ;;
-
+    log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
+    log_warning_msg "cannot re-read the config file (use restart)."
+  ;;
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+	echo "Usage: $NAME {start|stop|force-stop|restart|force-reload|status}" >&2
 	exit 1
 	;;
 esac
